### PR TITLE
[BUGFIX] enable image size 

### PR DESCRIPTION
**Pull request by davdenic**
This generate image size according to the width written in imagewidth or 
styles.content.textmedia.maxW or
styles.content.textmedia.maxWInText 

thanks

### CODE REVIEW

**Comment by alexanderschnitzler** [comment]
I don't really get what you want to do with this patch.

What it does, is that it respects `styles.content.textmedia.maxW` and does not render the original image size.

Let's say you have an image with a width of 3000 px and you set `styles.content.textmedia.maxW` to 2000, then without this patch, this extension renders the original (unprocessed) image with a width of 3000 px.

With this patch, the image width is capped to the value of `styles.content.textmedia.maxW`. Is that what you want to achieve? Because the title of this bugfix sounds different.

**Comment by davdenic** [comment]
Hi
it's exactly as you wrote.
with the patch it respects the image width written in the content image field or the maxW or maxWInText setted in TS.
i renamed the title. while the description seems clear enough.
thanks :)

**Comment by alexanderschnitzler** [comment]
Alright. I am about to add functional tests to this repository and I found another bug. I will take care of this but I might find another solution than you provided.

**Comment by davdenic** [comment]
the code was implemented in 7.6 and 8.x versions so i close the PR
thanks

**Pull request closed without merging**
