### PR TITLE
Make "fluid_styled_responsive_images" compatible to lazyloading-libraries (2nd approach)

### PR DESCRIPTION
**Pull request by stephankellermayr**
In order to use lazyload libraries, you need the attribute "data-srcset" instead of "srcset" (see: https://github.com/aFarkas/lazysizes). This could be achieved with some small changes.

Example typoscript:

``` typoscript
tt_content.textmedia.settings.responsive_image_rendering {
    layoutKey = srcset
    attributePrefix = data-
    sourceCollection {
        smallest {
            width = 264
            srcset = 264w
        }
        medium {
            width = 360
            srcset = 360w
        }
        large {
            width = 555
            srcset = 555w
        }
        larger {
            width = 737
            srcset = 737w
        }
        largest {
            width = 1140
            srcset = 1140w
            sizes = auto
        }
    }
}
```

### CODE REVIEW

**Comment by stephankellermayr** [comment]
...you can test these changes with the TYPO3-extension `lib_js_lazysizes`: https://github.com/sonority/lib_js_lazysizes

**Comment by alexanderschnitzler** [comment]
Looks good.
Don't you also need support for `data-src` as well?

**Comment by stephankellermayr** [comment]
That's a good question. In my special case (combining the features of your extension with `lib_js_lazysizes` and the configuration above) you don't need it. As you can see on https://github.com/aFarkas/lazysizes, the `data-src`-attribute is rarely in use (only in some special cases), so i don't think that it is really necessary if you were using `fluid_styled_responsive_images` with `(data-)srcset` AND `lib_js_lazysizes` (or any other lazyloading-lib) in the most common scenarios with TYPO3.  ...but i may be wrong. Maybe there is someone who wants to use it in another way. What do you think?

**Comment by stephankellermayr** [comment]
...but wait a second, i will test this usecase right now.

**Comment by stephankellermayr** [comment]
As far as is can see, it really makes no difference if you are using `src` or `data-src` with the javascript-library `lazysizes` in this setup.
Testet with:
- IE 10 & IE 11
- Edge 20 & Edge 25
- Latest Chrome/Firefox/Opera/midori on Linux

**Comment by stephankellermayr** [comment]
But on the other hand, i would keep the `src`-attribute to avoid some situations where a site is beeing ranked down because of missing image-attributes or alleged "improper" HTML.

**Comment by stephankellermayr** [comment]
Another approach could be, if the attributes for `src`, `srcset` and `sizes` were completely flexible via typoscript.
For example:

``` typoscript
 tt_content.textmedia.settings.responsive_image_rendering {
    layoutKey = srcset
    srcsetAttributes {
        src = data-src
        srcset = data-srcset
        sizes = data-sizes
    }
}
```

...what do you think?

**Comment by alexanderschnitzler** [comment]
I think that approach is a lot more flexible.

btw: what about the noscript pattern?
https://github.com/aFarkas/lazysizes#the-noscript-pattern

**Comment by stephankellermayr** [comment]
Do you really need this, if you have enabled `enableSmallDefaultImage` (which will generate a default image for the `src`-attribute)? ...i don't think so.

Btw: it would be great, if the default width of this generated image would be flexible too. Right now its hardcoded to `360m`. The variable `enableSmallDefaultImage` could be changed from boolean to string, which contains the width and in my oppinion it should be located in typoscript, not in `ext_conf_template.txt`.

**Comment by stephankellermayr** [comment]
OK, i will dig deeper into it and provide a new PR (3rd approach).

One more question: why did you set `enableSmallDefaultImage`? Is it just to generate valid HTML or was it for some other reason?

**Comment by stephankellermayr** [comment]
I have one more question: why did you change the variables `srcsetCandidate` to `srcset` and `mediaQuery` to `sizes`?
Would it not be better to stay as close as possible to the variables used in previous versions of TYPO3?

**Comment by alexanderschnitzler** [comment]
Answer 1:
I don't know if you need the noscript pattern. I am mostly a backend guy who had the need for responsive images. That's why this extension exists. However, I am really not into all the frontend stuff that is going on. So I better ask dumb questions. ;-)

Answer 2:
`enableSmallDefaultImage` is a feature for browsers that still need polyfills. That way, the `src` holds a quite small image instead of the regular sized one and only a small image is loaded on first hit. Maybe that is outdated meanwhile, last year I was told this is a good things to implement.

Answer 3:
Back then, when I had a look at what is possible in the browsers, there still coexisted many different approaches for responsive images. I didn't follow the recent browser updates and what emerges into the standard but back then I felt that srcset and sizes are the best way to deal with responsive images, unless you want to do artwork.

So, I had a look at the implementation for 6.2 and felt that the naming of variables was kind of odd, so I wanted to make them more meaningful. I don't see this extension as a successor of the core version, so I didn't see the need to stay compatible. I now know that this confuses a lot of people as they expect a similar configuration and I can't even tell them to RTFM as I don't have any.

**Comment by dbruening** [comment]
Hello, I would like to install your extension via TER and also use lazy loading. When will be the next update?
Thank you for your good job!

**Comment by alexanderschnitzler** [comment]
Good evening,
I am sorry but I have not been working on this extension for a long time and I am talking to people that are close to the core team to let them maintain this extension. So, I hope to be able to hand over the extension to a team of developers soon because I am not into frontend development any more at all.

**Comment by cedricziel** [comment]
This looks like an interesting proposition - thank you for taking the time for your PR. I am right now considering reviving it - would you mind rebasing your work on the current master @stephankellermayr ? Please don't hesitate to ask if you need help doing so.

**Comment by alexanderschnitzler** [comment]
@cedricziel Will you review this PR?

**Comment by cedricziel** [comment]
I hoped for a rebase - the PR then went out of sight, out of mind. I'll review it (hopefully) next week. Thx for the reminder.

**Comment by xerc** [comment]
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#Images_and_iframes

**Comment by xerc** [comment]
```
$ sed -i "/return \$this->buildImageTag/i \$options['additionalAttributes']['loading'] = 'lazy';" \
  source/typo3conf/ext/fluid_styled_responsive_images/Classes/Resource/Rendering/ImageRenderer.php
```

**Pull request closed without merging**
